name: Release APK

on:
  push:
    tag:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run:  |
          cd zay_chin_clone_app/mobile-frontend
          flutter pub get
          flutter pub upgrade
          flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

